version: '3.5'

services:

  styx-master:
    container_name: styx-master
    build: ./master
    ports: 
      - "7000:80"
    volumes:
      - "./master/server:/opt/server/"
      - "./shared:/opt/server/src/shared"
      - "/opt/server/node_modules"            
    environment:
      - NODE_ENV=development
    depends_on:
      - styx-consul-control

  styx-consul-control:
    container_name: styx-consul-control
    build: ./consul/control
    volumes: 
      - "./consul/control/config:/consul/config"
    ports: 
      - "8500:8500"
      - "8600:8600"
    depends_on:
      - styx-consul-server-1
      - styx-consul-server-2
      - styx-consul-server-3
    command: agent

  styx-consul-server-1: &styx-consul
    container_name: styx-consul-server-1
    build: ./consul
    volumes:
      - "./consul/server/config:/consul/config"
    depends_on:
      - styx-consul-agent-1
      - styx-consul-agent-2
      - styx-consul-agent-3                  
    command: agent
    
  styx-consul-server-2:
    <<: *styx-consul
    container_name: styx-consul-server-2

  styx-consul-server-3:
    <<: *styx-consul
    container_name: styx-consul-server-3

  styx-consul-agent-1: &styx-agent
    <<: *styx-consul
    container_name: styx-consul-agent-1
    ports: 
      - "6001:8500"
    volumes:
      - "./consul/agent/config/agent.json:/consul/config/agent.json"
      - "./consul/agent/config/db-1.json:/consul/config/db.json"
    depends_on:
      - styx-db-1
    command: agent

  styx-consul-agent-2:
    <<: *styx-agent
    container_name: styx-consul-agent-2
    ports: 
      - "6002:8500"    
    volumes:
      - "./consul/agent/config/db-2.json:/consul/config/db.json"    
    depends_on:
      - styx-db-2      

  styx-consul-agent-3:
    <<: *styx-agent
    container_name: styx-consul-agent-3
    ports: 
      - "6003:8500"    
    volumes:
      - "./consul/agent/config/db-3.json:/consul/config/db.json"    
    depends_on:
      - styx-db-3

  styx-consul-agent-4:
    <<: *styx-agent
    container_name: styx-consul-agent-4
    ports: 
      - "6004:8500"
    volumes:
      - "./consul/agent/config/db-4.json:/consul/config/db.json"    
    depends_on:
      - styx-db-4

  styx-consul-agent-5:
    <<: *styx-agent
    container_name: styx-consul-agent-5
    ports: 
      - "6005:8500"    
    volumes:
      - "./consul/agent/config/db-5.json:/consul/config/db.json"
    depends_on:
      - styx-db-5

  styx-db-1: &styx-db 
    container_name: styx-db-1
    build: ./db
    volumes:
      - "./db/server:/opt/server/"
      - "./shared:/opt/server/src/shared"      
      - "/opt/server/node_modules"                
    ports: 
      - "4001:80"    
    expose: 
      - "5432"
    environment:
      - NODE_ENV=development

  styx-db-2: 
    <<: *styx-db
    container_name: styx-db-2
    ports: 
      - "4002:80"    

  styx-db-3: 
    <<: *styx-db
    container_name: styx-db-3
    ports: 
      - "4003:80"        

  styx-db-4: 
    <<: *styx-db
    container_name: styx-db-4
    ports: 
      - "4004:80"        

  styx-db-5: 
    <<: *styx-db
    container_name: styx-db-5    
    ports: 
      - "4005:80"        